// Renders page 1 of a PDF to a PNG Blob so its QR code can be decoded.
// A visitor's entry pass, generated by qrPassPdf.ts, sometimes reaches the
// gate as the PDF itself rather than a screenshot — a guard forwarded the
// email attachment, or the visitor's phone opened it in a PDF viewer instead
// of the browser. Screenshotting it at the gate is not a workflow we want to
// depend on, so this turns page 1 straight into an image the existing QR
// decoder (decodeQrImage.ts) can read.
//
// Loads pdfjs-dist lazily, same as decodeQrImage.ts lazily imports
// qr-scanner, so the payload stays out of the initial bundle.
export type PdfPageRender =
  | { ok: true; blob: Blob }
  | { ok: false; reason: 'engine'; detail: string };

function describe(err: unknown): string {
  if (typeof err === 'string') return err;
  if (err instanceof Error) return `${err.name}: ${err.message}`;
  return String(err);
}

/** True when `file` is a PDF, by MIME type or (fallback) file extension. Some
 * browsers hand over an empty MIME type for a file picked from a phone's
 * downloads folder, which is why the extension is also checked. */
export function isPdfFile(file: File): boolean {
  if (file.type === 'application/pdf') return true;
  return file.name.toLowerCase().endsWith('.pdf');
}

const TARGET_WIDTH_PX = 1600;
const MIN_SCALE = 2;
const MAX_SCALE = 4;

/** Renders page 1 of `file` to a PNG Blob. Never throws — failures come back
 * as `{ ok: false, reason: 'engine' }`. */
export async function renderPdfFirstPage(file: File): Promise<PdfPageRender> {
  let pdf: import('pdfjs-dist').PDFDocumentProxy | undefined;
  let page: import('pdfjs-dist').PDFPageProxy | undefined;
  try {
    const pdfjs = await import('pdfjs-dist');
    pdfjs.GlobalWorkerOptions.workerSrc = new URL(
      'pdfjs-dist/build/pdf.worker.min.mjs',
      import.meta.url,
    ).toString();

    const data = await file.arrayBuffer();
    pdf = await pdfjs.getDocument({ data }).promise;
    page = await pdf.getPage(1);

    const baseViewport = page.getViewport({ scale: 1 });
    const scale = Math.min(MAX_SCALE, Math.max(MIN_SCALE, TARGET_WIDTH_PX / baseViewport.width));
    const viewport = page.getViewport({ scale });

    const canvas = document.createElement('canvas');
    canvas.width = Math.round(viewport.width);
    canvas.height = Math.round(viewport.height);
    const ctx = canvas.getContext('2d');
    if (!ctx) {
      const detail = 'canvas 2d context unavailable';
      console.error('[pdfQrPage] render failed:', detail);
      return { ok: false, reason: 'engine', detail };
    }

    await page.render({ canvas, canvasContext: ctx, viewport }).promise;

    const blob = await new Promise<Blob | null>((resolve) => {
      canvas.toBlob((b) => resolve(b), 'image/png');
    });
    if (!blob) {
      const detail = 'canvas.toBlob returned null';
      console.error('[pdfQrPage] render failed:', detail);
      return { ok: false, reason: 'engine', detail };
    }
    return { ok: true, blob };
  } catch (err) {
    const detail = describe(err);
    // Loud on purpose — an engine fault here is an app bug (bad worker wiring,
    // CSP block, corrupt PDF), not something to swallow silently.
    console.error('[pdfQrPage] render failed:', detail);
    return { ok: false, reason: 'engine', detail };
  } finally {
    page?.cleanup();
    await pdf?.loadingTask.destroy();
  }
}
